[project]
name = "eda-hw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hiplot>=0.1.33",
    "holidays>=0.97",
    "hvplot>=0.12.2",
    "ipython>=9.12.0",
    "jupyter-bokeh>=4.0.5",
    "lets-plot>=4.10.1",
    "lime>=0.2.0.1",
    "palmerpenguins>=0.1.6",
    "pandas>=2.3.3",
    "scikit-learn>=1.8.0",
    "setuptools==78.1.1",
    "shap>=0.52.0",
    "skimpy>=0.0.20",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "ipython>=9.12.0",
]
